/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: 
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.avinashdavid.marvelcomicviewer.api.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.*

/**
 * @property id The unique ID of the character resource.
 * @property name The name of the character.
 * @property description A short bio or description of the character.
 * @property modified The date the resource was most recently modified.
 * @property resourceURI The canonical URL identifier for this resource.
 * @property urls A set of public web site URLs for the resource.
 * @property thumbnail The representative image for this character.
 * @property comics A resource list containing comics which feature this character.
 * @property stories A resource list of stories in which this character appears.
 * @property events A resource list of events in which this character appears.
 * @property series A resource list of series in which this character appears.
 */
@JsonClass(generateAdapter = true)
data class Character(
    @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "modified") @field:Json(name = "modified") var modified: Date? = null,
    @Json(name = "resourceURI") @field:Json(name = "resourceURI") var resourceURI: String? = null,
    @Json(name = "urls") @field:Json(name = "urls") var urls: Array<Url>? = null,
    @Json(name = "thumbnail") @field:Json(name = "thumbnail") var thumbnail: Image? = null,
    @Json(name = "comics") @field:Json(name = "comics") var comics: ComicList? = null,
    @Json(name = "stories") @field:Json(name = "stories") var stories: StoryList? = null,
    @Json(name = "events") @field:Json(name = "events") var events: EventList? = null,
    @Json(name = "series") @field:Json(name = "series") var series: SeriesList? = null
)
