/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: 
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.avinashdavid.marvelcomicviewer.api.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type A description of the price (e.g. print price, digital price).
 * @property price The price (all prices in USD).
 */
@JsonClass(generateAdapter = true)
data class ComicPrice(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "price") @field:Json(name = "price") var price: Float? = null
)
