/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: 
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.avinashdavid.marvelcomicviewer.api.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.*

/**
 * @property type A description of the date (e.g. onsale date, FOC date).
 * @property date The date.
 */
@JsonClass(generateAdapter = true)
data class ComicDate(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "date") @field:Json(name = "date") var date: Date? = null
)
