/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: 
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.avinashdavid.marvelcomicviewer.api.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property resourceURI The path to the individual creator resource.
 * @property name The full name of the creator.
 * @property role The role of the creator in the parent entity.
 */
@JsonClass(generateAdapter = true)
data class CreatorSummary(
    @Json(name = "resourceURI") @field:Json(name = "resourceURI") var resourceURI: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "role") @field:Json(name = "role") var role: String? = null
)
