/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: 
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.avinashdavid.marvelcomicviewer.api.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.*

/**
 * @property id The unique ID of the event resource.
 * @property title The title of the event.
 * @property description A description of the event.
 * @property resourceURI The canonical URL identifier for this resource.
 * @property urls A set of public web site URLs for the event.
 * @property modified The date the resource was most recently modified.
 * @property start The date of publication of the first issue in this event.
 * @property end The date of publication of the last issue in this event.
 * @property thumbnail The representative image for this event.
 * @property comics A resource list containing the comics in this event.
 * @property stories A resource list containing the stories in this event.
 * @property series A resource list containing the series in this event.
 * @property characters A resource list containing the characters which appear in this event.
 * @property creators A resource list containing creators whose work appears in this event.
 * @property next A summary representation of the event which follows this event.
 * @property previous A summary representation of the event which preceded this event.
 */
@JsonClass(generateAdapter = true)
data class Event(
    @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "resourceURI") @field:Json(name = "resourceURI") var resourceURI: String? = null,
    @Json(name = "urls") @field:Json(name = "urls") var urls: Array<Url>? = null,
    @Json(name = "thumbnail") @field:Json(name = "thumbnail") var thumbnail: Image? = null,
    @Json(name = "comics") @field:Json(name = "comics") var comics: ComicList? = null,
    @Json(name = "stories") @field:Json(name = "stories") var stories: StoryList? = null,
    @Json(name = "series") @field:Json(name = "series") var series: SeriesList? = null,
    @Json(name = "characters") @field:Json(name = "characters") var characters: CharacterList? = null,
    @Json(name = "creators") @field:Json(name = "creators") var creators: CreatorList? = null,
    @Json(name = "next") @field:Json(name = "next") var next: EventSummary? = null,
    @Json(name = "previous") @field:Json(name = "previous") var previous: EventSummary? = null
)
