/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: 
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.avinashdavid.marvelcomicviewer.api.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property path The directory path of to the image.
 * @property extension The file extension for the image.
 */
@JsonClass(generateAdapter = true)
data class Image(
    @Json(name = "path") @field:Json(name = "path") var path: String? = null,
    @Json(name = "extension") @field:Json(name = "extension") var extension: String? = null
)
