/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: 
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.avinashdavid.marvelcomicviewer.api.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property code The HTTP status code of the returned result.
 * @property status A string description of the call status.
 * @property copyright The copyright notice for the returned result.
 * @property attributionText The attribution notice for this result.  Please display either this notice or the contents of the attributionHTML field on all screens which contain data from the Marvel Comics API.
 * @property attributionHTML An HTML representation of the attribution notice for this result.  Please display either this notice or the contents of the attributionText field on all screens which contain data from the Marvel Comics API.
 * @property `data` The results returned by the call.
 * @property etag A digest value of the content returned by the call.
 */
@JsonClass(generateAdapter = true)
data class StoryDataWrapper(
    @Json(name = "code") @field:Json(name = "code") var code: Int? = null,
    @Json(name = "status") @field:Json(name = "status") var status: String? = null,
    @Json(name = "copyright") @field:Json(name = "copyright") var copyright: String? = null,
    @Json(name = "attributionText") @field:Json(name = "attributionText") var attributionText: String? = null,
    @Json(name = "attributionHTML") @field:Json(name = "attributionHTML") var attributionHTML: String? = null,
    @Json(name = "data") @field:Json(name = "data") var `data`: StoryDataContainer? = null,
    @Json(name = "etag") @field:Json(name = "etag") var etag: String? = null
)
