/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: 
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.avinashdavid.marvelcomicviewer.api.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.*

/**
 * @property id The unique ID of the story resource.
 * @property title The story title.
 * @property description A short description of the story.
 * @property resourceURI The canonical URL identifier for this resource. 
 * @property type The story type e.g. interior story, cover, text story.
 * @property modified The date the resource was most recently modified.
 * @property thumbnail The representative image for this story.
 * @property comics A resource list containing comics in which this story takes place.
 * @property series A resource list containing series in which this story appears.
 * @property events A resource list of the events in which this story appears.
 * @property characters A resource list of characters which appear in this story.
 * @property creators A resource list of creators who worked on this story.
 * @property originalissue A summary representation of the issue in which this story was originally published.
 */
@JsonClass(generateAdapter = true)
data class Story(
    @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "resourceURI") @field:Json(name = "resourceURI") var resourceURI: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "thumbnail") @field:Json(name = "thumbnail") var thumbnail: Image? = null,
    @Json(name = "comics") @field:Json(name = "comics") var comics: ComicList? = null,
    @Json(name = "series") @field:Json(name = "series") var series: SeriesList? = null,
    @Json(name = "events") @field:Json(name = "events") var events: EventList? = null,
    @Json(name = "characters") @field:Json(name = "characters") var characters: CharacterList? = null,
    @Json(name = "creators") @field:Json(name = "creators") var creators: CreatorList? = null,
    @Json(name = "originalissue") @field:Json(name = "originalissue") var originalissue: ComicSummary? = null
)
