/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: 
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.avinashdavid.marvelcomicviewer.api.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type The canonical type of the text object (e.g. solicit text, preview text, etc.).
 * @property language The IETF language tag denoting the language the text object is written in.
 * @property text The text.
 */
@JsonClass(generateAdapter = true)
data class TextObject(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "language") @field:Json(name = "language") var language: String? = null,
    @Json(name = "text") @field:Json(name = "text") var text: String? = null
)
