/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: 
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.avinashdavid.marvelcomicviewer.api.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type A text identifier for the URL.
 * @property url A full URL (including scheme, domain, and path).
 */
@JsonClass(generateAdapter = true)
data class Url(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "url") @field:Json(name = "url") var url: String? = null
)
